name: Keep Alive
on:
  schedule:
    - cron: '0 0 1 * *' # 每月1号自动运行
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Empty commit to keep repo active
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git commit --allow-empty -m "Auto keepalive commit"
          git push
